import 'dart:async';

import 'package:flame_audio/flame_audio.dart';
import 'package:flutter/foundation.dart';

/// The four sounds CLAUDE.md asks for. Generated by `tool/make_sounds.dart`.
/// No screaming, no comedy sounds.
class Sfx {
  const Sfx._();

  /// A soft thud on landing.
  static const String land = 'land.wav';

  /// A whoosh on flip, the signature mechanic.
  static const String flip = 'flip.wav';

  /// A click on jump.
  static const String jump = 'jump.wav';

  /// A dull thump on death.
  static const String death = 'death.wav';

  static const List<String> all = [land, flip, jump, death];
}

/// The background bed, so a quiet stretch of track is never silent. One loop,
/// eight seconds long, generated by the same tool as the sound effects.
class Music {
  const Music._();

  static const String loop = 'music.wav';
}

/// Fire and forget sound. Every call is guarded, because a missing or
/// unavailable audio backend must never take the game down with it: the
/// puzzle still works in silence.
class SoundPlayer {
  SoundPlayer({required this.enabled, this.musicEnabled = false});

  final bool enabled;
  final bool musicEnabled;

  bool _ready = false;

  /// The background player is a single global, so this is only ever set up
  /// once however many levels are opened and closed.
  static bool _bgmReady = false;

  Future<void> preload() async {
    if (!enabled || _ready) return;
    try {
      await FlameAudio.audioCache.loadAll(Sfx.all);
      _ready = true;
    } catch (error) {
      debugPrint('Pitchpole: audio unavailable, playing silent ($error)');
    }
  }

  /// Starts the loop from the top. Quiet, because it plays under everything.
  Future<void> startMusic({double volume = 0.32}) async {
    if (!musicEnabled) return;
    try {
      if (!_bgmReady) {
        FlameAudio.bgm.initialize();
        _bgmReady = true;
      }
      await FlameAudio.bgm.stop();
      await FlameAudio.bgm.play(Music.loop, volume: volume);
    } catch (error) {
      debugPrint('Pitchpole: music unavailable, playing silent ($error)');
    }
  }

  Future<void> stopMusic() async {
    if (!_bgmReady) return;
    try {
      await FlameAudio.bgm.stop();
    } catch (_) {
      // Nothing to do: the level still plays in silence.
    }
  }

  void play(String asset, {double volume = 1}) {
    if (!enabled || !_ready) return;
    unawaited(
      FlameAudio.play(asset, volume: volume).then(
        (_) {},
        onError: (Object _) {},
      ),
    );
  }
}
