import 'dart:async';

import 'package:flame_audio/flame_audio.dart';
import 'package:flutter/foundation.dart';

/// The four sounds CLAUDE.md asks for. Generated by `tool/make_sounds.dart`.
/// No screaming, no comedy sounds.
class Sfx {
  const Sfx._();

  /// A soft thud on landing.
  static const String land = 'land.wav';

  /// A whoosh on flip, the signature mechanic.
  static const String flip = 'flip.wav';

  /// A click on jump.
  static const String jump = 'jump.wav';

  /// A dull thump on death.
  static const String death = 'death.wav';

  static const List<String> all = [land, flip, jump, death];
}

/// The background bed, so a quiet stretch of track is never silent. One loop,
/// eight seconds long, generated by the same tool as the sound effects.
class Music {
  const Music._();

  static const String loop = 'music.wav';
}

/// Fire and forget sound. Every call is guarded, because a missing or
/// unavailable audio backend must never take the game down with it: the level
/// still plays in silence.
///
/// Sounds come out of a warm [AudioPool] per effect rather than through
/// `FlameAudio.play`. That call builds a fresh `AudioPlayer`, hands it an
/// audio context, sets a release mode and only then loads and plays the
/// asset — four platform round trips before a click that is meant to land on
/// the frame the button was pressed. A pool has the players built and the
/// source already set, so playing is a volume change and a resume.
///
/// The pools are static and warmed once for the whole app. Rebuilding them
/// per level would just move the stutter to the start of every level.
class SoundPlayer {
  SoundPlayer({required this.enabled, this.musicEnabled = false});

  final bool enabled;
  final bool musicEnabled;

  /// How many players each effect keeps ready, and the ceiling before spare
  /// players are released instead of pooled.
  static const int _minPlayers = 2;
  static const int _maxPlayers = 4;

  /// Low latency players never report completion, so a clip is handed back to
  /// its pool by hand. Comfortably longer than the longest sound, which a
  /// test in `sound_assets_test.dart` holds under 500 ms.
  static const Duration _recycleAfter = Duration(milliseconds: 700);

  static final Map<String, AudioPool> _pools = {};

  /// In flight warm up, so two callers never build the pools twice.
  static Future<void>? _warming;

  static bool _bgmReady = false;

  /// Builds every sound pool. Safe to call as often as you like: the work
  /// happens once. Call it at start up so the first jump of the first level
  /// is as quick as the thousandth.
  static Future<void> warmUp() {
    if (_pools.isNotEmpty) return Future<void>.value();
    return _warming ??= _buildPools();
  }

  static Future<void> _buildPools() async {
    try {
      await FlameAudio.audioCache.loadAll(Sfx.all);
      for (final sfx in Sfx.all) {
        _pools[sfx] = await AudioPool.create(
          source: AssetSource(sfx),
          audioCache: FlameAudio.audioCache,
          minPlayers: _minPlayers,
          maxPlayers: _maxPlayers,
          // Maps to the platform's short sound path, which is the one built
          // for latency rather than for long files.
          playerMode: PlayerMode.lowLatency,
          audioContext: AudioContextConfig(
            focus: AudioContextConfigFocus.mixWithOthers,
          ).build(),
        );
      }
    } catch (error) {
      debugPrint('Pitchpole: audio unavailable, playing silent ($error)');
      _pools.clear();
    } finally {
      _warming = null;
    }
  }

  Future<void> preload() async {
    if (!enabled) return;
    await warmUp();
  }

  void play(String asset, {double volume = 1}) {
    if (!enabled) return;
    final pool = _pools[asset];
    if (pool == null) return;
    unawaited(_fire(pool, volume));
  }

  static Future<void> _fire(AudioPool pool, double volume) async {
    try {
      final stop = await pool.start(volume: volume);
      await Future<void>.delayed(_recycleAfter);
      await stop();
    } catch (_) {
      // A sound that will not play is not worth interrupting a run for.
    }
  }

  /// Starts the loop from the top. Quiet, because it plays under everything.
  Future<void> startMusic({double volume = 0.32}) async {
    if (!musicEnabled) return;
    try {
      if (!_bgmReady) {
        FlameAudio.bgm.initialize();
        _bgmReady = true;
      }
      await FlameAudio.bgm.stop();
      await FlameAudio.bgm.play(Music.loop, volume: volume);
    } catch (error) {
      debugPrint('Pitchpole: music unavailable, playing silent ($error)');
    }
  }

  Future<void> stopMusic() async {
    if (!_bgmReady) return;
    try {
      await FlameAudio.bgm.stop();
    } catch (_) {
      // Nothing to do: the level still plays in silence.
    }
  }
}
