import 'dart:async';

import 'package:flame_audio/flame_audio.dart';
import 'package:flutter/foundation.dart';

/// The four sounds CLAUDE.md asks for. Generated by `tool/make_sounds.dart`.
/// No screaming, no comedy sounds.
class Sfx {
  const Sfx._();

  /// A soft thud on landing.
  static const String land = 'land.wav';

  /// A whoosh on flip, the signature mechanic.
  static const String flip = 'flip.wav';

  /// A click on jump.
  static const String jump = 'jump.wav';

  /// A dull thump on death.
  static const String death = 'death.wav';

  /// A short rise on reaching the door.
  static const String win = 'win.wav';

  static const List<String> all = [land, flip, jump, death, win];
}

/// The background bed, so a quiet stretch of track is never silent. One loop,
/// eight seconds long, generated by the same tool as the sound effects.
class Music {
  const Music._();

  static const String loop = 'music.wav';
}

/// How loud each sound is against the others.
///
/// Every file is written at the same peak by `tool/make_sounds.dart`, so these
/// are the whole mix and nothing else affects it. That is deliberate: the
/// balance used to be split between a multiplier buried in each synth function
/// and a volume at each call site, which meant nobody could see it.
///
/// What the numbers are protecting: the sounds that fire constantly — the
/// click of a jump, the thud of a landing, the tick of a coin — sit well under
/// the ones that happen once, or a long level becomes a rattle. The two that
/// are allowed to be loud are the two that end a run.
class Mix {
  const Mix._();

  /// The signature mechanic, but a whoosh rather than a hit.
  static const double flip = 0.75;

  /// Both fire many times a level.
  static const double jump = 0.55;
  static const double land = 0.6;

  /// A light tick under everything: there are up to forty coins in a level.
  static const double coin = 0.3;

  /// The two that end a run.
  static const double death = 1;
  static const double win = 0.95;

  /// Under all of it. Quiet by design, but no longer inaudible: the file it
  /// scales used to be more than five times below full scale, so this being
  /// low was never what made the music hard to hear.
  static const double music = 0.4;
}

/// Fire and forget sound. Every call is guarded, because a missing or
/// unavailable audio backend must never take the game down with it: the level
/// still plays in silence.
///
/// Sounds come out of a warm [AudioPool] per effect rather than through
/// `FlameAudio.play`. That call builds a fresh `AudioPlayer`, hands it an
/// audio context, sets a release mode and only then loads and plays the
/// asset — four platform round trips before a click that is meant to land on
/// the frame the button was pressed. A pool has the players built and the
/// source already set, so playing is a volume change and a resume.
///
/// The pools are static and warmed once for the whole app. Rebuilding them
/// per level would just move the stutter to the start of every level.
class SoundPlayer {
  SoundPlayer({required this.enabled, this.musicEnabled = false});

  final bool enabled;
  final bool musicEnabled;

  /// How many players each effect keeps ready, and the ceiling before spare
  /// players are released instead of pooled.
  static const int _minPlayers = 2;
  static const int _maxPlayers = 4;

  /// Low latency players never report completion, so a clip is handed back to
  /// its pool by hand. Comfortably longer than the longest sound, which a
  /// test in `sound_assets_test.dart` holds under 500 ms.
  static const Duration _recycleAfter = Duration(milliseconds: 700);

  static final Map<String, AudioPool> _pools = {};

  /// In flight warm up, so two callers never build the pools twice.
  static Future<void>? _warming;

  /// In flight initialisation of the background player, shared the same way
  /// [_warming] is, so two levels starting at once configure it once.
  static Future<void>? _bgmInit;

  /// There is one background player for the whole app, but [SoundPlayer] is
  /// built per level. Whichever level started the music owns it, and is the
  /// only one allowed to stop it.
  ///
  /// Without this the music dies on the first level change. Moving to the
  /// next level replaces the route, so the incoming level's `onLoad` starts
  /// the music and *then* the outgoing level's `onRemove` stops it — leaving
  /// every level after the first one silent for the rest of the session.
  static Object? _musicOwner;

  /// Whether the loop is already running, so a level change lets it play on
  /// rather than restarting it eight seconds from the top.
  static bool _musicPlaying = false;

  /// Builds every sound pool. Safe to call as often as you like: the work
  /// happens once. Call it at start up so the first jump of the first level
  /// is as quick as the thousandth.
  static Future<void> warmUp() {
    if (_pools.isNotEmpty) return Future<void>.value();
    return _warming ??= _buildPools();
  }

  static Future<void> _buildPools() async {
    try {
      await FlameAudio.audioCache.loadAll(Sfx.all);
      for (final sfx in Sfx.all) {
        _pools[sfx] = await AudioPool.create(
          source: AssetSource(sfx),
          audioCache: FlameAudio.audioCache,
          minPlayers: _minPlayers,
          maxPlayers: _maxPlayers,
          // Maps to the platform's short sound path, which is the one built
          // for latency rather than for long files.
          playerMode: PlayerMode.lowLatency,
          audioContext: AudioContextConfig(
            focus: AudioContextConfigFocus.mixWithOthers,
          ).build(),
        );
      }
    } catch (error) {
      debugPrint('Pitchpole: audio unavailable, playing silent ($error)');
      _pools.clear();
    } finally {
      _warming = null;
    }
  }

  Future<void> preload() async {
    if (!enabled) return;
    await warmUp();
  }

  void play(String asset, {double volume = 1}) {
    if (!enabled) return;
    final pool = _pools[asset];
    if (pool == null) return;
    unawaited(_fire(pool, volume));
  }

  static Future<void> _fire(AudioPool pool, double volume) async {
    try {
      final stop = await pool.start(volume: volume);
      await Future<void>.delayed(_recycleAfter);
      await stop();
    } catch (_) {
      // A sound that will not play is not worth interrupting a run for.
    }
  }

  /// Starts the loop, or leaves it running if a previous level already did.
  Future<void> startMusic({double volume = Mix.music}) async {
    if (!musicEnabled) return;

    // Claimed before the first await, so an outgoing level that stops the
    // music a moment from now finds it already belongs to this one.
    _musicOwner = this;

    try {
      // Awaited, unlike before. This sets the player's audio context, and
      // letting it race with the play below is enough on its own to leave the
      // player configured but silent.
      await (_bgmInit ??= FlameAudio.bgm.initialize());

      // Something else claimed the music while that was in flight.
      if (!identical(_musicOwner, this)) return;
      if (_musicPlaying) return;

      _musicPlaying = true;
      await FlameAudio.bgm.play(Music.loop, volume: volume);
    } catch (error) {
      _musicPlaying = false;
      // Dropped rather than kept, so a failure here is not cached for the rest
      // of the session and the next level gets to try again.
      _bgmInit = null;
      debugPrint('Pitchpole: music unavailable, playing silent ($error)');
    }
  }

  /// Which [SoundPlayer] currently owns the background loop, or null if
  /// nothing does.
  @visibleForTesting
  static Object? get debugMusicOwner => _musicOwner;

  /// Stops the loop, but only on behalf of the level that started it.
  Future<void> stopMusic() async {
    if (!identical(_musicOwner, this)) return;
    _musicOwner = null;
    _musicPlaying = false;
    try {
      await FlameAudio.bgm.stop();
    } catch (_) {
      // Nothing to do: the level still plays in silence.
    }
  }
}
